skip_checks:
  - CKV_AWS_20
soft_fail: true
download_external_modules: true
external_modules_download_path: .external_modules
use_enforcement_rules: true
enforcement_rules:
  CKV_AWS_20:
    severity: MEDIUM
